name: Build with xmake

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            plat: linux
            artifact_dir: linux/x64/release
          - name: Windows
            os: windows-latest
            plat: windows
            artifact_dir: windows/x64/release
    env:
      XMAKE_ROOT: y
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libglfw3-dev \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev

      - name: Set up xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Cache xmake packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake/packages
          key: ${{ runner.os }}-xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            ${{ runner.os }}-xmake-

      - name: Update xmake repositories
        run: xmake repo -u

      - name: Configure build
        run: xmake config --mode=release --arch=x64 --plat=${{ matrix.plat }} -y

      - name: Build project
        run: xmake build

      - name: Upload binaries
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-binaries
          path: build/${{ matrix.artifact_dir }}/
          if-no-files-found: error
